/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    // 강제로 포함할 클래스들 (핫딜 사이트에서 사용되는 주요 클래스들)
    'bg-gradient-to-r',
    'from-pink-100',
    'to-blue-100',
    'from-green-100', 
    'to-yellow-100',
    'from-purple-100',
    'to-pink-100',
    'bg-red-100',
    'bg-red-500',
    'bg-blue-500',
    'bg-green-500',
    'bg-orange-500',
    'bg-purple-500',
    'text-red-600',
    'text-blue-600',
    'text-green-600',
    'text-orange-600',
    'text-purple-600',
    'text-white',
    'hover:bg-blue-600',
    'hover:shadow-lg',
    'shadow-md',
    'shadow-lg',
    'rounded-lg',
    'rounded-xl',
    'p-4',
    'p-6',
    'px-4',
    'py-2',
    'mx-auto',
    'grid',
    'grid-cols-1',
    'md:grid-cols-2',
    'lg:grid-cols-3',
    'gap-4',
    'gap-6',
    'flex',
    'items-center',
    'justify-between',
    'space-x-2',
    'text-sm',
    'text-lg',
    'text-xl',
    'font-bold',
    'font-medium',
    'line-clamp-2',
  ],
  theme: {
    extend: {
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'bounce-subtle': 'bounceSubtle 0.6s ease-in-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        bounceSubtle: {
          '0%, 20%, 50%, 80%, 100%': { transform: 'translateY(0)' },
          '40%': { transform: 'translateY(-2px)' },
          '60%': { transform: 'translateY(-1px)' },
        },
      },
    },
  },
  plugins: [],
}

